spring:
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  quartz:
    # 使用数据库存储
    job-store-type: jdbc
    jdbc:
      # 是否自动使用 SQL 初始化 Quartz 表结构。这里设置成 never ，手动创建表结构
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            clusterCheckinInterval: 20000
            dataSource: myDS
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            selectWithLockSQL: SELECT * FROM {0}LOCKS WHERE LOCK_NAME = ? FOR UPDATE
            tablePrefix: QRTZ_
            useProperties: true
          plugin:
            shutdownhook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
            triggHistory:
              class: org.quartz.plugins.history.LoggingJobHistoryPlugin
          scheduler:
            batchTriggerAcquisitionMaxCount: 50
            instanceId: AUTO
            instanceName: Job_Crontab_Quartz_Scheduler
            skipUpdateCheck: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 50

ribbon:
  ServerListRefreshInterval: 3000

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    # 使用spring cloud stream rabbitmq, 禁用掉springboot的rabbitmq health检查
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,configprops,env,beans,conditions,loggers,metrics,mappings,prometheus,scheduledtasks,info,refresh,busrefresh,bindings
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
      probes:
        enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
    conditions:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true
    scheduledtasks:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    busrefresh:
      enabled: true
server:
  port: 19805
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

